### PR TITLE
Updated Demo Service example to be a "System"

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
# XRTK - Mixed Reality Toolkit Pull Request

## Overview
Updated Demo Service example to be a "System" following:

- https://github.com/XRTK/XRTK-Core/pull/871

Also updated Demo System profile to remove registeredServiceProvidersProfile

## Changes

- Updated CustomSystem implementation to a system

## Breaking Changes

- Breaks

## Related Submodule Changes

Depends on
- - https://github.com/XRTK/XRTK-Core/pull/871

### CODE REVIEW

**Comment by StephenHodgson** [comment]
Why does this need to be a system?

**Comment by StephenHodgson** [comment]
Could we add a demo system as well as keeping the old demo service?

**Comment by SimonDarksideJ** [comment]
Sure, however, it will likely confuse things, given Services are only accessible in COde where Systems are registerable through the Editor.

More likely we need an example scene showing these implementations and their uses.  So we'll handle that in a separate PR.

**Comment by StephenHodgson** [comment]
> given Services are only accessible in code where Systems are registerable through the Editor.

This is not true. That's why I asked to revert the registered service profile changes in the other PR.

@FejZa has been using lots of services in the editor and same with a few of my own projects. Just want to see minimal changes with a comparable workflow.

**Comment by SimonDarksideJ** [comment]
Then I'll drop this PR and remake it to just be a service.  Anything further will need a separate PR as this was to only enable Examples to be built with Core.

**Comment by SimonDarksideJ** [comment]
Tried reverting to just a "Service" implementation, but as it is ONLY a service and cannot have configuration, I have updated the example to show both implementations instead.

**Pull request closed without merging**
